#!/usr/bin/env node
// Assert this engine still implements the canonical scan-secrets contract.
//
// The scan-level parity harness (js_reference_dump / py_reference_dump /
// parity_compare) answers "do both engines agree about fixtures/". That is a
// real check and it stays, but it is exactly as good as the corpus: it cannot
// see a divergence the corpus does not exercise.
//
// It did not. On 2026-07-21 the canonical DEFAULT_INCLUDE gained `**/*.env.*`
// and `**/*.cfg`; this port did not, and fixtures/ contained neither
// extension, so run_parity.ps1 printed ALL GREEN for eight days while the
// browser demo, the CLI and the Action all silently stopped looking at
// `.env.local` and `setup.cfg` -- measured on one directory: canonical 3
// findings, this engine 1, the missed one an AWS key.
//
// This compares the LISTS instead of a sample of their effects. It needs no
// Python and no access to the canonical source, so unlike the parity harness
// it runs in this repo's CI on every push.
//
// parity/contract.json is generated by the canonical repo
// (`scripts/export_scan_contract.py --write`) and copied here verbatim. Do not
// hand-edit it: a contract edited to match the code checks nothing.
//
// Usage: node scripts/contract_check.mjs [path/to/contract.json]
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { SECRET_RULES, DEFAULT_INCLUDE, DEFAULT_EXCLUDE, MAX_FILE_BYTES } from "../scan.js";
import { contractDigest } from "./contract_digest.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const CONTRACT_PATH = process.argv[2] || join(HERE, "..", "parity", "contract.json");
const SUPPORTED_CONTRACT_VERSION = 1;

const contract = JSON.parse(readFileSync(CONTRACT_PATH, "utf-8"));

const failures = [];
const fail = (msg) => failures.push(msg);

// --- 0. the document itself ------------------------------------------------
// Refuse a shape this checker does not know rather than reading the fields it
// recognises and reporting PASS on a document it only half understood.
if (contract.contract_version !== SUPPORTED_CONTRACT_VERSION) {
  console.log(
    `FAIL  contract_version ${contract.contract_version} is not supported ` +
      `(this checker knows ${SUPPORTED_CONTRACT_VERSION}) -- update scripts/contract_check.mjs`,
  );
  process.exit(1);
}

// The digest proves the file was produced by the exporter and not edited by
// hand to make this script go quiet.
{
  const { digest, ...core } = contract;
  const recomputed = contractDigest(core);
  if (recomputed !== digest) {
    fail(`digest mismatch: file says ${digest?.slice(0, 16)}, content hashes to ${recomputed.slice(0, 16)} -- the contract has been edited by hand`);
  }
}

// --- 1. rules --------------------------------------------------------------
// Python compiles with re.MULTILINE; JS spells that "m". Rule sources are kept
// byte-identical to the Python originals, so the only permitted transform is
// the inline "(?i)" prefix, which JS cannot express inline.
function translate(pythonRegex) {
  if (pythonRegex.startsWith("(?i)")) {
    return { source: pythonRegex.slice(4), flags: "gim" };
  }
  return { source: pythonRegex, flags: "gm" };
}

const jsById = new Map(SECRET_RULES.map((r) => [r.id, r]));
const contractIds = contract.rules.map((r) => r.id);

if (JSON.stringify(SECRET_RULES.map((r) => r.id)) !== JSON.stringify(contractIds)) {
  // Order matters: findings are emitted rule-outer, so a reordering changes
  // the per-file finding order the parity comparison depends on.
  fail(`rule ids or their order diverge:\n    contract: ${contractIds.join(", ")}\n    engine:   ${SECRET_RULES.map((r) => r.id).join(", ")}`);
}

for (const expected of contract.rules) {
  const actual = jsById.get(expected.id);
  if (!actual) {
    fail(`rule missing from the engine: ${expected.id}`);
    continue;
  }
  const want = translate(expected.regex);
  if (actual.source !== want.source) {
    fail(`rule ${expected.id}: regex source differs\n    contract: ${want.source}\n    engine:   ${actual.source}`);
  }
  if (actual.flags !== want.flags) {
    fail(`rule ${expected.id}: flags ${actual.flags} != ${want.flags}`);
  }
  if (actual.severity !== expected.severity) {
    fail(`rule ${expected.id}: severity ${actual.severity} != ${expected.severity}`);
  }
  if (actual.message !== expected.message) {
    fail(`rule ${expected.id}: message differs\n    contract: ${expected.message}\n    engine:   ${actual.message}`);
  }
  // A source that does not compile would otherwise only surface at scan time.
  try {
    new RegExp(actual.source, actual.flags);
  } catch (err) {
    fail(`rule ${expected.id}: source does not compile in JS (${err.message})`);
  }
}

// --- 2. glob lists ---------------------------------------------------------
// This is where the 2026-07-21 drift lived. Compared as ordered lists: the
// order is not semantically load-bearing for matching, but a reorder is still
// a divergence from the canonical file and worth a look.
compareList("DEFAULT_INCLUDE", contract.include, DEFAULT_INCLUDE);
compareList("DEFAULT_EXCLUDE", contract.exclude, DEFAULT_EXCLUDE);

function compareList(name, expected, actual) {
  const missing = expected.filter((p) => !actual.includes(p));
  const extra = actual.filter((p) => !expected.includes(p));
  for (const p of missing) fail(`${name}: missing pattern present in the contract: ${p}`);
  for (const p of extra) fail(`${name}: pattern not in the contract: ${p}`);
  if (missing.length === 0 && extra.length === 0 && JSON.stringify(expected) !== JSON.stringify(actual)) {
    fail(`${name}: same patterns, different order`);
  }
}

// --- 3. scalars ------------------------------------------------------------
if (MAX_FILE_BYTES !== contract.max_file_bytes) {
  fail(`MAX_FILE_BYTES ${MAX_FILE_BYTES} != ${contract.max_file_bytes}`);
}
if (!contract.python_compile_flags.includes("MULTILINE")) {
  fail(`contract no longer compiles with MULTILINE; every rule here still carries the "m" flag`);
}

// --- report ----------------------------------------------------------------
for (const f of failures) console.log(`FAIL  ${f}`);
console.log(
  `contract check: ${contract.rules.length} rules, ${contract.include.length} include, ` +
    `${contract.exclude.length} exclude, digest ${String(contract.digest).slice(0, 16)} -- ` +
    `${failures.length ? `${failures.length} divergence(s), FAIL` : "PASS"}`,
);
if (failures.length) {
  console.log("\nthe contract is canonical. Fix scan.js to match it, or regenerate the");
  console.log("contract in the canonical repo and copy the new file here.");
}
process.exit(failures.length ? 1 : 0);
